"""Fix cyclic dependency with chooser_id

Revision ID: 0533db55f339
Revises: ab9468d642c0
Create Date: 2025-07-01 20:00:42.370039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0533db55f339'
down_revision = 'ab9468d642c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('game_sessions_chooser_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_chooser_id', 'players', ['chooser_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chooser_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('game_sessions_chooser_id_fkey'), 'players', ['chooser_id'], ['id'])

    # ### end Alembic commands ###
