"""is_connected added to PLayer model

Revision ID: 06110f6f0089
Revises: bb73687615eb
Create Date: 2025-07-23 10:26:53.933894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06110f6f0089'
down_revision = 'bb73687615eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('is_connected')

    # ### end Alembic commands ###
