"""model GivenAnswer adapted to cascade deleting

Revision ID: 46221b077114
Revises: 7276bc8c9002
Create Date: 2025-07-23 18:12:12.462559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46221b077114'
down_revision = '7276bc8c9002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers_given', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answers_given_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers_given', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answers_given_player_id_fkey'), 'players', ['player_id'], ['id'])

    # ### end Alembic commands ###
