"""models Round and GameSession adapted to cascade deleting

Revision ID: 7276bc8c9002
Revises: 7f8b7ed8102e
Create Date: 2025-07-23 18:09:58.136576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7276bc8c9002'
down_revision = '7f8b7ed8102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rounds_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rounds_session_id_fkey'), 'game_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
