"""Admin model added

Revision ID: 786d8bbfc741
Revises: 46221b077114
Create Date: 2025-07-24 16:09:48.181484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786d8bbfc741'
down_revision = '46221b077114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
