"""ondelete cascade added to Player model, session_id

Revision ID: 7f8b7ed8102e
Revises: e7479b902986
Create Date: 2025-07-23 18:07:01.296525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8b7ed8102e'
down_revision = 'e7479b902986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('players_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('players_session_id_fkey'), 'game_sessions', ['session_id'], ['id'])

    # ### end Alembic commands ###
