"""chooser added to gamesession

Revision ID: ab9468d642c0
Revises: f8fb887b0843
Create Date: 2025-07-01 19:05:28.640357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9468d642c0'
down_revision = 'f8fb887b0843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chooser_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'players', ['chooser_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chooser_id')

    # ### end Alembic commands ###
