"""Add chooser_id to Round

Revision ID: bb73687615eb
Revises: 0533db55f339
Create Date: 2025-07-09 17:35:49.233702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb73687615eb'
down_revision = '0533db55f339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chooser_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_round_chooser_id', 'players', ['chooser_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_constraint('fk_round_chooser_id', type_='foreignkey')
        batch_op.drop_column('chooser_id')

    # ### end Alembic commands ###
