"""add ondelete cascade to answers.question_id

Revision ID: e7479b902986
Revises: dce245ef0761
Create Date: 2025-07-23 17:01:32.474534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7479b902986'
down_revision = 'dce245ef0761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('answers_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('answers_question_id_fkey'), 'questions', ['question_id'], ['id'])

    # ### end Alembic commands ###
